---
version: "3"
services:
  # Prometheus
  prometheus:
    image: bitnami/prometheus:2.35.0
    container_name: prometheus
    command: >
      --config.file=/opt/bitnami/prometheus/conf/prometheus.yml
      --storage.tsdb.path=/opt/bitnami/prometheus/data
      --web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries
      --web.console.templates=/opt/bitnami/prometheus/conf/consoles
      --web.enable-lifecycle
    volumes:
      - ../../../deploy/resources/config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - "9090:9090"
