---
replicaCount: 2

auth:
  username: "request-rabbit"
  existingPasswordSecret: "notarization-credentials"
  existingSecretPasswordKey: "rabbitmq-password"

extraPlugins: "rabbitmq_prometheus rabbitmq_stomp rabbitmq_web_stomp rabbitmq_auth_backend_oauth2 rabbitmq_auth_backend_cache rabbitmq_amqp1_0"

ingress:
  enabled: true
  hostname: test-not.xfsc.dev
  path: "/rabbitmq/(.*)"
  tls: true
  certManager: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production-http
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
