apiVersion: v1
kind: ConfigMap
metadata:
  name: train-enrollment-configmap
  namespace: {{ .Release.Namespace }}
data:
  FLYWAY_JDBC_URL: "{{ .Values.config.datasourceJdbcUrl }}"
  QUARKUS_DATASOURCE_JDBC_URL: "{{ .Values.config.datasourceJdbcUrl }}"
  QUARKUS_DATASOURCE_USERNAME: "{{ .Values.config.datasourceUsername }}"
  QUARKUS_HTTP_ACCESS_LOG_ENABLED: "true"
  QUARKUS_HTTP_PORT: "{{ .Values.service.port }}"
  QUARKUS_LOG_LEVEL: "WARN"
  QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.otelConnectorUrl }}"
  QUARKUS_OIDC_CLIENT_GRANT_TYPE: "password"
  QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_PASSWORD_USERNAME: "{{ .Values.config.oidcClientGrantOptionsUsername }}"
  QUARKUS_OIDC_CLIENT_CLIENT_ID: "{{ .Values.config.oidcClientId }}"
  QUARKUS_REST_CLIENT_TRAIN_ENROLLMENT_URL: "{{ .Values.config.restClientTrainEnrollmentUrl }}"
  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: "{{ .Values.config.oidcAuthServerUrl }}"
