version: '3.8'

services:
  #
  # Client
  #
  ledger-client:
    image: ledger-base
    build:
      context: ./ledger
    command: ./scripts/start_client.sh
    environment:
      - IP=10.0.0.101
    networks:
      indy:
        ipv4_address: 10.0.0.2
    volumes:
      - client-data:/home/indy/.indy_client
      - ./ledger/tmp:/tmp

  #
  # Webserver
  #
  ledger-browser:
    image: ledger-base
    build:
      context: ./ledger
    command: bash -c 'sleep 10 && ./scripts/start_webserver.sh'
    environment:
      - IP=10.0.0.101
      - REGISTER_NEW_DIDS=True
      - LEDGER_INSTANCE_NAME=Notarization Service Ledger
      - WEB_ANALYTICS_SCRIPT=
      - INFO_SITE_TEXT=Gaia-X @ GitLab
      - INFO_SITE_URL=https://gitlab.com/gaia-x/data-infrastructure-federation-services/not
    networks:
      indy:
        ipv4_address: 10.0.0.3
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - ./ledger/server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger

  #
  # Nodes
  #
  ledger-nodes:
    image: ledger-base
    build:
      context: ./ledger
    command: ./scripts/start_nodes.sh
    networks:
      indy:
        ipv4_address: 10.0.0.101
    ports:
      - "9701:9701"
      - "9702:9702"
      - "9703:9703"
      - "9704:9704"
      - "9705:9705"
      - "9706:9706"
      - "9707:9707"
      - "9708:9708"
    environment:
      - IP=10.0.0.101
    volumes:
      - nodes-data:/home/indy/ledger

networks:
  indy:
    name: ledger_network
    external: true

volumes:
  client-data:
  webserver-cli:
  webserver-ledger:
  nodes-data:
