---
replicaCount: 1

image:
  tag: "latest-dev"

ingress:
  enabled: true
  certManager: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: CHANGEME
      paths:
        - path: "/revocation/(.*)"
          pathType: ImplementationSpecific
  tls:
   - secretName: tls-secret-not-accept
     hosts:
       - CHANGEME

config:
  datasourceJdbcUrl: CHANGEME
  datasourceUsername: CHANGEME
  datasourceExistingSecret: "notarization-credentials"
  datasourceSecretKey: "postgresql-not-api-password"
  otelConnectorUrl: CHANGEME
  restClientRevocationApiUrl: CHANGEME
  # restClientSsiIssuanceApiUrl: "http://ssi-issuance.not-accept.svc.cluster.local:8088"
  revocationBaseUrl: CHANGEME
  revocationMinIssueInterval: CHANGEME
