name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  JAVA_CACHE_KEY: notarization-api-java-cache
  JAVA_TMP_CACHE_KEY: notarization-api-java-cache-${{ github.ref_name }}

jobs:
  check-draft:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - name: Check if PR is Draft or WIP
        id: check
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^(WIP|Draft).* ]]; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi
        if: github.event_name == 'pull_request'

  compile:
    needs: check-draft
    if: needs.check-draft.outputs.should_skip == 'false'
    uses: ./.github/workflows/java-compile-job.yml
    with:
      java-cache-key: ${{ env.JAVA_CACHE_KEY }}
      java-tmp-cache-key: ${{ env.JAVA_TMP_CACHE_KEY }}
    secrets: inherit

  # test:
  #   needs: compile
  #   uses: ./.github/workflows/java-test-job.yml
  #   with:
  #     java-cache-key: ${{ env.JAVA_CACHE_KEY }}
  #   secrets: inherit

  # image-build:
  #   needs: test
  #   uses: ./.github/workflows/java-image-job.yml
  #   secrets: inherit

  # release:
  #   needs: image-build
  #   uses: ./.github/workflows/helm-build-job.yml
  #   secrets: inherit

  # build-3rd-party:
  #   needs: release
  #   uses: ./.github/workflows/3rd-party-image-job.yml
  #   secrets: inherit

  # ssi-issuance:
  #   needs: build-3rd-party
  #   uses: ./.github/workflows/ssi-issuance.yml
  #   secrets: inherit