name: Build and Test

on:
  workflow_dispatch:
  release:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-draft:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - name: Check if PR is Draft or WIP
        id: check
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^(WIP|Draft).* ]]; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

  compile:
    needs: check-draft
    if: needs.check-draft.outputs.should_skip == 'false'
    uses: ./.github/workflows/java-compile-job.yml
    with:
        java-cache-key: notarization-api-java-cache
        java-tmp-cache-key: notarization-api-java-cache-${{ github.ref_name }}
    secrets: inherit

  test:
     needs: compile
     uses: ./.github/workflows/java-test-job.yml
     with:
        java-cache-key: notarization-api-java-cache
        java-tmp-cache-key: notarization-api-java-cache-${{ github.ref_name }}
     secrets: inherit

  # image-build:
  #   needs: test
  #   uses: ./.github/workflows/java-image-job.yml
  #   secrets: inherit

  # release:
  #   needs: image-build
  #   uses: ./.github/workflows/helm-build-job.yml
  #   secrets: inherit

  # build-3rd-party:
  #   needs: release
  #   uses: ./.github/workflows/3rd-party-image-job.yml
  #   secrets: inherit