#!/bin/bash

# Create a single sql migration script given a number of sql scripts.

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

SCRIPT_NAME=$(basename $0)

TARGET_DIR="deploy/db-init-dev"
TARGET_FILE="${TARGET_DIR}/init.sql"
SOURCE_DIR="deploy/db-flyway"

# The array of ordered sql scripts
SQL_SCRIPTS=("V1.0.0__Initial_state.sql")

cd "${SCRIPT_DIR}/.."

mkdir -p "${TARGET_DIR}"

echo "*" > "${TARGET_DIR}/.gitignore"

echo "-- This script is generated by ${SCRIPT_NAME}" > "${TARGET_FILE}"

for sql_script in "${SQL_SCRIPTS[@]}"
do
    echo "Apending flyway migration ${sql_script}"
    cat "${SOURCE_DIR}/${sql_script}" >> "${TARGET_FILE}"
done
